# --- Main Colors ---
background            #0a1519
foreground            #d9e4eb
cursor                #d9e4eb
cursor_text_color     #0a1519

selection_background  #2c4a60
selection_foreground  #cbe6ff

url_color             #acc8f8

# --- ANSI Colors ---
color0                #0a1519
color1                #ffb4ab
color2                #acc8f8
color3                #accae5
color4                #5bd4ff
color5                #acc8f8
color6                #accae5
color7                #d9e4eb

color8                #3d484e
color9                #93000a
color10               #2b4770
color11               #2c4a60
color12               #004d62
color13               #2c4a60
color14               #2b4770
color15               #bdc8ce

# --- Starship Prompt Bubbles ---
color255              #004d62
color254              #5bd4ff
color253              #2c4a60
color252              #accae5
color251              #2b4770
color250              #acc8f8
color249              #93000a
color248              #ffb4ab

color232              #baeaff
color233              #003545
color234              #cbe6ff
color235              #143349
color236              #d5e3ff
color237              #113158
color238              #ffdad6
color239              #690005
color240              #baeaff

# Matched with unthemed light/dark
color243              #5bd4ff
color244              #ffb4ab
color245              #3d484e

# --- UI Elements ---
active_tab_foreground   #003545
active_tab_background   #5bd4ff
inactive_tab_foreground #baeaff
inactive_tab_background #004d62

active_border_color     #5bd4ff
inactive_border_color   #879298

# --- Marks ---
mark1_foreground        #001f29
mark1_background        #baeaff
mark2_foreground        #001e30
mark2_background        #cbe6ff
mark3_foreground        #001b3c
mark3_background        #d5e3ff
