background {
    monitor =
    path = $HOME/Pictures/Wallpapers/evening_sky.png
    blur_passes = 2
    blur_size = 7
    nosie = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
}

input-field {
    monitor =
    size = 200, 50
    outline_thickness = 3
    outer_color = rgba(30, 30, 46, 1)
    inner_color = rgba(0, 0, 0, 0.2)
    font_color = #cba6f7
    dots_size = 0.33 
    dots_spacing = 0.15 
    dots_center = false
    fade_on_empty = false
    position = 0, 80
    halign = center
    valign = bottom
}

label {
    monitor =
    text = $TIME
    color = rgba(30, 30, 46, 1)
    font_size = 120
    font_family = JetBrainsMono Nerd
    position = 0, 80
    halign = center 
    valign = center
}

